---

- name: Install Java 
  package: name=java-1.8.0-openjdk state=installed

- name: add group tomcat
  group: name=tomcat

- name: add user tomcat
  user: name=tomcat group=tomcat home=/opt/apache-tomcat-8.0.50 createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: 
    url: http://apache.cp.if.ua/tomcat/tomcat-8/v8.5.29/bin/apache-tomcat-8.5.29.tar.gz 
    dest: /opt/apache-tomcat-8.5.29.tar.gz
    mode: 0664
   
- name: Extract archive
  command: chdir=/usr/share /bin/tar xzf /opt/apache-tomcat-8.5.29.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.29

- name: change owner 
  file: path=/opt/apache-tomcat-8.5.29 owner=tomcat group=tomcat state=directory recurse=yes


- name: Configure Tomcat users
  template: src=tomcat-users.xml.j2 dest=/opt/apache-tomcat-8.5.29/conf/tomcat-users.xml
  notify: restart tomcat

- name: Configure Admin
  copy:
     src: context.xml
     dest: /opt/apache-tomcat-8.5.29/webapps/manager/META-INF/context.xml
     mode: 0664

- name: Copy War file
  copy:
    src: hello-epam.war
    dest: /opt/apache-tomcat-8.5.29/webapps/hello-epam.war
    mode: 0644
  notify: restart tomcat


- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes  
