---

- name: Install Java 
  package: name=java-1.8.0-openjdk state=installed

- name: add group tomcat
  group: name=tomcat

- name: add user tomcat
  user: name=tomcat group=tomcat home=/opt/apache-tomcat-{{ tomcat_version }} createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: 
    url: http://apache.cp.if.ua/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz 
    dest: /opt/apache-tomcat-{{ tomcat_version }}.tar.gz
    mode: 0664
   
- name: Extract archive
  unarchive:
    src: /opt/apache-tomcat-{{ tomcat_version }}.tar.gz
    dest: /opt/apache-tomcat-{{ tomcat_version }}
    remote_src: yes

- name: change owner 
  file: path=/opt/apache-tomcat-{{ tomcat_version }} owner=tomcat group=tomcat state=directory recurse=yes


- name: Configure Tomcat users
  template: src=tomcat-users.xml.j2 dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/tomcat-users.xml
  notify: restart tomcat

- name: Configure Admin
  copy:
     src: context.xml
     dest: /opt/apache-tomcat-{{ tomcat_version }}/webapps/manager/META-INF/context.xml
     mode: 0664

- name: Copy War file
  copy:
    src: hello-epam.war
    dest: /opt/apache-tomcat-{{ tomcat_version }}/webapps/hello-epam.war
    mode: 0644
  notify: restart tomcat


- name: Install Tomcat init script
  template: src=tomcat-initscript.sh.j2 dest=/etc/init.d/tomcat mode=0755

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes  
