---
- name: install tomcat in yum
  package: name={{ item  }} state=installed
  with_items: 
    - tomcat8
    - tomcat8-webapps
    - tomcat8-admin-webapps

- name: Configure Tomcat users
  template: src=tomcat-users.xml.j2 dest=/etc/tomcat8/tomcat-users.xml
  notify: restart tomcat

#- name: Configure server.xml
#  template: src=server.xml.j2 dest=/etc/tomcat8/server.xml
#  notify: restart tomcat

- name: Configure Admin 
  copy:
     src: context.xml
     dest: /usr/share/tomcat8/webapps/manager/META-INF/context.xml
     mode: 0664
  notify: restart tomcat

- name: Copy War file
  copy:
    src: hello-epam.war
    dest: /usr/share/tomcat8/webapps/hello-epam.war
    mode: 0644
  notify: restart tomcat

- name: start tomcat
  service: name=tomcat8 state=started
